# Generated by Django 5.2.4 on 2025-08-09 06:34

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique coupon code', max_length=50, unique=True)),
                ('type', models.CharField(choices=[('PRODUCT_DISCOUNT', 'Product Discount'), ('MIN_PRODUCT_QUANTITY', 'Minimum Product Quantity'), ('SHIPPING_DISCOUNT', 'Shipping Discount'), ('CART_TOTAL_DISCOUNT', 'Cart Total Discount'), ('FIRST_TIME_USER', 'First Time User'), ('USER_SPECIFIC', 'User Specific')], default='PRODUCT_DISCOUNT', max_length=25)),
                ('discount_percent', models.DecimalField(decimal_places=2, help_text='Discount percentage (0-100)', max_digits=5)),
                ('min_quantity_required', models.PositiveIntegerField(default=1, help_text='Minimum quantity required to apply coupon')),
                ('min_cart_total', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum cart total required for CART_TOTAL_DISCOUNT', max_digits=10, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, help_text='Coupon becomes valid from this date and time')),
                ('expires_at', models.DateTimeField(help_text='Coupon expiration date and time')),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cart_subtotal', models.DecimalField(decimal_places=2, default=0, help_text='Subtotal before shipping and discounts', max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Confirmation'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('tracking_number', models.CharField(blank=True, help_text='Tracking number for order tracking', max_length=100, null=True)),
                ('customer_name', models.CharField(help_text='Required customer name', max_length=100)),
                ('customer_email', models.EmailField(help_text='Required customer email', max_length=254)),
                ('customer_phone', models.CharField(help_text='Required customer phone number', max_length=50)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_account_number', models.CharField(help_text='Required backend-set account number', max_length=50)),
                ('sender_number', models.CharField(help_text="Required customer's payment number", max_length=50)),
                ('transaction_id', models.CharField(help_text='Required transaction/Reference ID', max_length=100)),
                ('payment_method', models.CharField(choices=[('bkash', 'bKash'), ('nagad', 'Nagad'), ('card', 'Card')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Order Payment',
                'verbose_name_plural': 'Order Payments',
            },
        ),
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Confirmation'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], max_length=20)),
                ('notes', models.TextField(blank=True, help_text="e.g., 'Package has left the warehouse.'", null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., By Air, By Ship, Door to Door', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Base price (used if no tiers defined)', max_digits=10)),
                ('delivery_estimated_time', models.CharField(blank=True, help_text="e.g., '1-2 days', '5-7 days', '2-3 weeks'", max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_quantity', models.PositiveIntegerField(help_text='Minimum quantity required for this pricing tier')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price for this quantity tier', max_digits=10)),
            ],
            options={
                'verbose_name': 'Shipping Tier',
                'verbose_name_plural': 'Shipping Tiers',
                'ordering': ['min_quantity'],
            },
        ),
    ]
