# Generated by Django 5.2.4 on 2025-08-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique coupon code', max_length=50, unique=True)),
                ('type', models.CharField(choices=[('PRODUCT_DISCOUNT', 'Product Discount'), ('MIN_PRODUCT_QUANTITY', 'Minimum Product Quantity'), ('SHIPPING_DISCOUNT', 'Shipping Discount')], default='PRODUCT_DISCOUNT', max_length=25)),
                ('discount_percent', models.DecimalField(decimal_places=2, help_text='Discount percentage (0-100)', max_digits=5)),
                ('min_quantity_required', models.PositiveIntegerField(default=1, help_text='Minimum quantity required to apply coupon')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Coupon expiration date and time')),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'ordering': ['-created_at'],
            },
        ),
    ]
