# Generated by Django 5.2.4 on 2025-08-03 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingmethod',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Base price (used if no tiers defined)', max_digits=10),
        ),
        migrations.CreateModel(
            name='ShippingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_quantity', models.PositiveIntegerField(help_text='Minimum quantity required for this pricing tier')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price for this quantity tier', max_digits=10)),
                ('shipping_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_tiers', to='orders.shippingmethod')),
            ],
            options={
                'verbose_name': 'Shipping Tier',
                'verbose_name_plural': 'Shipping Tiers',
                'ordering': ['min_quantity'],
                'unique_together': {('shipping_method', 'min_quantity')},
            },
        ),
    ]
