# Generated by Django 5.2.4 on 2025-08-03 15:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_shippingmethod_price_shippingtier'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='valid_from',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Coupon becomes valid from this date and time'),
        ),
    ]
