# Generated by Django 5.2.4 on 2025-08-03 15:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_coupon_valid_from'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='eligible_users',
            field=models.ManyToManyField(blank=True, help_text='Users eligible for USER_SPECIFIC coupons', related_name='specific_coupons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coupon',
            name='min_cart_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum cart total required for CART_TOTAL_DISCOUNT', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='type',
            field=models.CharField(choices=[('PRODUCT_DISCOUNT', 'Product Discount'), ('MIN_PRODUCT_QUANTITY', 'Minimum Product Quantity'), ('SHIPPING_DISCOUNT', 'Shipping Discount'), ('CART_TOTAL_DISCOUNT', 'Cart Total Discount'), ('FIRST_TIME_USER', 'First Time User'), ('USER_SPECIFIC', 'User Specific')], default='PRODUCT_DISCOUNT', max_length=25),
        ),
    ]
