# Generated by Django 5.2.4 on 2025-08-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_coupon_eligible_users_coupon_min_cart_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart_subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Subtotal before shipping and discounts', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_email',
            field=models.EmailField(blank=True, help_text='Customer email for guest orders', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(blank=True, help_text='Customer name for guest orders', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(blank=True, help_text='Customer phone for guest orders', max_length=50, null=True),
        ),
    ]
