# Generated by Django 5.2.4 on 2025-08-08 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_cart_subtotal_order_customer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingmethod',
            name='delivery_estimated_time',
            field=models.CharField(blank=True, help_text="e.g., '1-2 days', '5-7 days', '2-3 weeks'", max_length=50, null=True),
        ),
    ]
