# Generated by Django 5.2.4 on 2025-08-09 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_make_personal_info_required'),
        ('users', '0003_alter_user_options_remove_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(help_text='Shipping address', on_delete=django.db.models.deletion.PROTECT, to='users.address', null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='sender_number',
            field=models.CharField(help_text="Required customer's payment number", max_length=50),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='transaction_id',
            field=models.CharField(help_text='Required transaction/Reference ID', max_length=100),
        ),
    ]
