# Generated by Django 5.2.4 on 2025-08-09 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_shipping_address_and_more'),
        ('users', '0003_alter_user_options_remove_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, help_text='Shipping address', null=True, on_delete=django.db.models.deletion.PROTECT, to='users.address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_method',
            field=models.ForeignKey(blank=True, help_text='Shipping method', null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.shippingmethod'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, help_text='Tracking number for order tracking', max_length=100, null=True),
        ),
    ]
