# Generated by Django 5.2.4 on 2025-07-18 09:25

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAdditionalDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor.fields.RichTextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_descriptions', to='products.product')),
            ],
            options={
                'verbose_name': 'ProductAdditionalDescription',
                'verbose_name_plural': 'ProductAdditionalDescriptions',
            },
        ),
        migrations.CreateModel(
            name='ProductAdditionalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/additional_images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='products.product')),
            ],
            options={
                'verbose_name_plural': 'Product Additional Images',
            },
        ),
    ]
