# Generated by Django 5.2.4 on 2025-08-02 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
    ]
