# Generated by Django 5.2.4 on 2025-07-30 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_brand_color_product_brand_product_colors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='colors',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
    ]
