# Generated by Django 5.2.4 on 2025-08-02 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ['-created_at']},
        ),
    ]
